### ISSUE TITLE
RGBD cams

### ISSUE THREAD

**Issue by caseybasichis** [freemocap/freemocap#122]
Any plans for mixing in RGBD cameras?

**Comment by Jaegermeiste** [comment]
+1 for Kinect V2 via libfreenect2

**Comment by trentwirth** [comment]
Depth cameras are something we've talked about, I think that it would be especially useful for research applications (i.e., the ones that we designed FreeMoCap for in the first place!). However, I don't expect our core devs to get to that for quite some time. The current priority is getting an API finished so that FreeMoCap is leaner, more flexible, and user friendly. 

Jon is planning a dev update soon where he'll lay out the priorities in more detail, but it's really good to know that there are folks interested in this! If you haven't already, join our discord. I think conversations like this will happen more fluidly there :)
