### ISSUE TITLE
using IP cameras instead of USB webcams

### ISSUE THREAD

**Issue by danialldev** [freemocap/freemocap#146]
Hi, is it possible to use IP cameras instead of USB webcams?

**Comment by jonmatthis** [comment]
That's what these folks are doing: https://discord.com/channels/760487252379041812/760489542888194138/983808011799785503

At the moment, their work flow is get videos from their IP camera system, synchronize it manually (so that each video has the exact same number of frames), put them in a folder with this structure:
```
[freemocap_data_folder]
|--[session_id]
|--|--'SynchedVideos'
```

And then processing that folder with:

```python
import freemocap
freemocap.RunMe(sessionID=[sessionID], stage=3)
```

If that sounds like too much of a pain for you, just hold on for a few months and we should have much better support for that kind of thing :)

**Comment by danialldev** [comment]
> That's what these folks are doing: https://discord.com/channels/760487252379041812/760489542888194138/983808011799785503
> 
> At the moment, their work flow is get videos from their IP camera system, synchronize it manually (so that each video has the exact same number of frames), put them in a folder with this structure:
> 
> ```
> [freemocap_data_folder]
> |--[session_id]
> |--|--'SynchedVideos'
> ```
> 
> And then processing that folder with:
> 
> ```python
> import freemocap
> freemocap.RunMe(sessionID=[sessionID], stage=3)
> ```
> 
> If that sounds like too much of a pain for you, just hold on for a few months and we should have much better support for that kind of thing :)

thanks, yes I was considering doing the same thing, but if time sync and video trimming was also automated with ip cameras would have been great.
