### ISSUE TITLE
freemocap-env v0.0.54 pose_landmark_heavy.tflite - HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by mjhmilla** [freemocap/freemocap#251]
When running freemocap-env it fails when trying to download pose_landmark_heavy.tflite  from google. I looked in the code and found two potential problems: 

---------------------
1. In download_utils.py _OSS_URL_PREFIX is https://github.com/google/mediapipe/raw/master

If I put https://github.com/google/mediapipe/raw/master in a browser I also get a 404 error. If instead 'raw' is replaced with 'tree' then the link works fine. I tried making this change in _OSS_URL_PREFIX in download_utils.py, but this didn't fix the problem.

2. The path that the file is being downloaded to is listed in the terminal as

C:\Users\norma\.conda\envs\freemocap-env\lib\site-packages\mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite

This path contains a mix of back slashes, and forward slashes ... which might cause problems once the https error 404 is fixed.
---------------------

The output from the terminal is attached. 

Thank you again for your efforts!

@mjhmilla

freemocap-env\lib\site-packages\mediapipe\python\solutions\download_u │
│ tils.py:32 in download_oss_model  

[freemocap-env_errorMessage20220922.txt](https://github.com/freemocap/freemocap/files/9683004/freemocap-env_errorMessage20220922.txt)

**Comment by jonmatthis** [comment]
Hey! Thanks for your interest in this project and for sleuthing around this problem!

Good news is that this issue can be fixed by simply upgrading mediapipe with `pip install mediapipe --upgrade`

My understanding is that the `mediapipe` folks shifted around the location of the model when they updated to `v0.8.11` but any previous version of mediapipe will still try to download the model from the old location (so you were on the right track with what you said in your first point, I think ) 

let me know if that works!

**Comment by mjhmilla** [comment]
Thank you very much - updating the mediapipe did the trick, everything works now!!! : )
