### ISSUE TITLE
About jitter problem

### ISSUE THREAD

**Issue by henrycjh** [freemocap/freemocap#289]
Thanks for your great work, I have watched the video you showed in README, it is really impressive.
I notice that the result of FreeMocap in that video has extremely stable feet, but I know that the results from MediaPipe or OpenPose do not have such stable feet. I am wondering if it is possible for you to give me some suggestions on the methods you used in your project.
Thanks for your attention!

**Comment by jonmatthis** [comment]
Hi, thank you!!

> I notice that the result of FreeMocap in that video has extremely stable feet, but I know that the results from MediaPipe or OpenPose do not have such stable feet. 

It's probably because we're using multiple camera and triangulating  the 3d based the multiple 2d viewpoints 

If you are getting your data based on estimates from a single camera, the skeleton tracking algorithm can estimate the 2D position of a keypoint using image information, but if it wants to guess at depth it has to guess (i.e. make an "inference" based on other statistics )

With a multi-view method like ours, we are *measuring* the depth of each tracked point by combining the 2D estimates from  each camera with information about the camera's 6DoF position (measured via calibration, e.g. with [anipose](https://anipose.org)

One goal of `freemocap` is to build itself in a modular enough way that it's easy to 'slot in' whatever 2d tracking algorithm you want (mediapipe, openpose, deeplabcut, etc) to do the pose estimation from the camera images, and let `freemocap` handle the synchronization/triangulation, etc. I'm *really * close to done with a new refactor of the software that will get us much closer to that goal, so stick around if you want to use it!

Come join the Discord for the earliest updates :)  - https://discord.gg/SgdnzbHDTG

**Comment by henrycjh** [comment]
Thanks for your reply. I am looking forward to it !
