### ISSUE TITLE
How to get freemocap running on windws

### ISSUE THREAD

**Issue by mbxymail** [freemocap/freemocap#365]
Is there an tutorial showing how to install and run freemocap on windows.

**Comment by messiasof** [comment]
Yes, [there is](https://freemocap.readthedocs.io/en/latest/how_to_guides/how_to_install_and_run_the_alpha_gui/)

These instructions are for `alpha` version (aka 0.1.0 and onwards), it may still be unstable for now, it's a work-in-progress
for more stable version you can use `pre-alpha`: [Instructions here.](https://freemocap.readthedocs.io/en/latest/how_to_guides/how_to_use_the_pre-alpha_code/) Don't worry, it is very similar to the instructions that I will give.

**Instructions (Latest Freemocap Version):**
- Install [Git for Windows](https://git-scm.com/download/win)
- Install [Anaconda](https://www.anaconda.com/products/distribution) (or [Miniconda](https://docs.conda.io/en/latest/miniconda.html) that takes less space and it's faster to install) 
- After installation, open the "Anaconda Prompt" (just search it in Start Menu)
- Type: `conda create -n freemocap-gui python=3.9` in order to create your virtual enviroment where Freemocap will run
- The program may ask if you want to install the necessary dependencies, such as pip and python itself. Just type `y` and wait
- Type `conda activate freemocap-gui` in order to initialize that enviroment
- Clone the repository by typing `git clone https://github.com/freemocap/freemocap` and wait
- Navigate into that newly cloned/downloaded folder by typing `cd freemocap`
- Now, install the dependencies by typing `pip install -r requirements.txt` and wait again
- Done! Freemocap is installed!
- Type `python freemocap\__main__.py` to run Freemocap

From now on, to open the program next time, just open the Anaconda Prompt and write:
`conda activate freemocap-gui`
`cd freemocap`
`python freemocap\__main__.py`

Hope it helps! :)

Note for advanced users:
--
You don't necessarily need to use the anaconda prompt, just any one that is anconda-enabled. These instructions try to be as easy and objective as possible.

**Comment by philipqueen** [comment]
@messiasof did a great job summing up the windows install at the time. Now we have the release candidate working quite well, and the instructions here are the best to follow: https://github.com/freemocap/freemocap#quickstart
To have the most recent bug fixes, you can use whichever version is most recent here: https://pypi.org/project/freemocap/1.0.0rc0/#history At the time of writing it's 1.0.12rc

We also have updated docs coming very soon, so we will not have a variety of conflicting install instructions.
