### ISSUE TITLE
Does it support exporting to bvh files？

### ISSUE THREAD

**Issue by dhs964057117** [freemocap/freemocap#376]
I am a beginner in this field, and I hope my questions are not so foolish.
My question is, is there a way to export the captured animation as a BVH file?

**Comment by philipqueen** [comment]
Hello, currently there is no way to output to BVH. That is something we could look into outputting though if there is not an existing tool to convert the blender output to bvh.

**Comment by philipqueen** [comment]
Hi @dhs964057117, the workflow for getting a BVH file from Freemocap data would be to output the freemocap data to Blender (happens automatically when you process a session), target an armature with the data (a good current workflow can be found here: https://www.youtube.com/watch?v=i7n_jOFy5LY), and then export it to a bvh using Blender.

Because a BVH file needs an armature, and freemocap data is not tied to an armature, it's not something we can add at this time. We can revisit it if we eventually get an automated pipeline from freemocap to an armature.

**Comment by dhs964057117** [comment]
> 你好@dhs964057117，从 Freemocap 数据获取 BVH 文件的工作流程是将 freemocap 数据输出到 Blender（在处理会话时自动发生），用数据定位一个骨架（一个很好的当前工作流程可以在这里找到：https: [// www.youtube.com/watch?v=i7n_jOFy5LY](https://www.youtube.com/watch?v=i7n_jOFy5LY) )，然后使用 Blender 将其导出到 bvh。
> 
> 因为 BVH 文件需要一个骨架，而 freemocap 数据没有绑定到骨架，所以我们现在不能添加它。如果我们最终获得从 freemocap 到骨架的自动化管道，我们可以重新访问它。

thanks for a lot , i will try it
