### ISSUE TITLE
YOLO cropping method

### ISSUE THREAD

**Issue by philipqueen** [freemocap/freemocap#384]

**Comment by jonmatthis** [comment]
Aaron and philip tested it and it didn't work properly (was old code)

- We are putting this in the backlog for now because I think this will happen automatically when we use mmpose 

- but apparently there's a facebook cropping thing (facebookresearch/segment-anything)? Lets not worry abot that for now, because I think mmlab capture the fucntionality we need (via YOLO i think?)

**Comment by trentwirth** [comment]
Continued in #526
