### ISSUE TITLE
Add LabStreamingLayer events

### ISSUE THREAD

**Issue by JuliusWelzel** [freemocap/freemocap#491]
Hi,

I am really impressed with to toolbox. I would like to propose adding the option to send out string markers to synchronize the video data with other modalities. The easiest way of doing this is might be to send out [LSL markers](https://github.com/labstreaminglayer/pylsl/blob/master/pylsl/examples/SendStringMarkers.py#L21) when the video recording is started and stopped. It might be easiest to create a subthread which runs the LSL outlet and initates markers the same time the logging is taking place.
Is this something that is best added in the [skellycam package VideoRecorder](https://github.com/freemocap/skellycam/blob/ee6f2bcc4ea71c626f302ec1babc06650655bfe3/skellycam/opencv/video_recorder/video_recorder.py#L16)?

I am happy to start working on this to improve usability with other devices.

**Comment by philipqueen** [comment]
Hi @JuliusWelzel, looking at the code of pylsl, it does seem pretty simple to send out start recording and stop recording markers. Would that be sufficient? Or does it need to send out markers with each frame in order to synchronize properly with other devices?

I think you're right that it would fit best in skellycam. Making a fork and getting a working proof of concept would be a great place to start. Skellycam is getting a bit of a rework currently, so I wouldn't put too much effort into making it clean, as the code will likely change before merging your changes, but if you get it working in this state it likely won't be hard to adapt it to the new changes. As far as where to start, I would look at this class, as what you pointed to records the videos to disk, but isn't necessarily running while the video is recording: https://github.com/freemocap/skellycam/blob/main/skellycam/opencv/group/strategies/grouped_process_strategy.py

One consideration for including it would be if it requires an external (non-python) dependency. I understand it will to use the LSL feature, which makes sense, but whatever solution potentially ends up in the code shouldn't force any user to download LSL just to get skellycam/freemocap running.

**Comment by JuliusWelzel** [comment]
Hi,

i have added an instance of an LSL outlet [here](https://github.com/JuliusWelzel/skellycam/blob/7c3fb3b69dbd67785878711524753459c6b264e4/skellycam/opencv/group/strategies/grouped_process_strategy.py#L21). When the `GrouepProcessStrategy` is initiated, the LSL outlet is [opened](https://github.com/JuliusWelzel/skellycam/blob/7c3fb3b69dbd67785878711524753459c6b264e4/skellycam/opencv/group/strategies/grouped_process_strategy.py#L33). Finally when the recording is started, the outlet [sends a simple trigger](https://github.com/JuliusWelzel/skellycam/blob/7c3fb3b69dbd67785878711524753459c6b264e4/skellycam/opencv/group/strategies/grouped_process_strategy.py#L62) to LSL.

**Comment by JuliusWelzel** [comment]
[PR](https://github.com/freemocap/skellycam/pull/40) is live. We can continue with the integration on the PR?

**Comment by JuliusWelzel** [comment]
@philipqueen How did it go? If you want some background on LSL, we can also have an online meeting about this. The easiest way to collect LSL data (string markers in this case) is through the [LabRecorder](https://github.com/labstreaminglayer/App-LabRecorder).

**Comment by philipqueen** [comment]
@JuliusWelzel Sorry for the delay, just commented my main feedback on the PR

**Comment by jonmatthis** [comment]
conversation continued in skellycam -https://github.com/freemocap/skellycam/pull/40
