### ISSUE TITLE
High memory usage during mediapipe pose detection

### ISSUE THREAD

**Issue by raphCode** [freemocap/freemocap#527]
I processed around 2 minutes of 1080p 60fps footage (ca. 7000 frames) and noticed a high RAM (~40GB) usage during the pose detection stage. I also had to disable the multiprocessing option in order not to exceed the available system memory.

I examined the code. Here is what I suspect is responsible for the high memory usage:
https://github.com/freemocap/freemocap/blob/7616f65d18dcf192f70f538027f712db5e73e37f/freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/mediapipe_skeleton_detector.py#L174-L175
That code block is in a loop iterating over the video frames. For each frame, the pose is detected, and an annotated frame is created, which is held in `video_annotated_images_list`. After the whole video is processed, the annotated video is saved to disk.

Effectively, this holds raw, uncompressed images of the (annotated) footage in RAM.

I suggest to write the annotated video out frame-by-frame without holding all frames in RAM first. This could be done
- interleaved with the mediapipe pose detection
- alternatively, after all frames have been processed by mediapipe: iterating the video frames again, annotating them on-the-fly from the saved pose data

The second option could even run in its own thread to speed up the whole mocap pipeline. Afaik, no later part critically depends on the annotated videos? (Only the blend file maybe)

I can contribute a fix if that is helpful.

**Comment by philipqueen** [comment]
Hi @raphCode, sorry for the delay in responding to this one. You're right that we're storing the entire videos in RAM at this point, which is definitely not ideal. Our next release will feature control over how many processes are spun up, so you hopefully won't have to decide between full multiprocessing and no multiprocessing.

As for the core of your issue though: In the next release this specific code will be offloaded to skellytracker, so that's where any short term development should be: https://github.com/freemocap/skellytracker/blob/main/skellytracker/trackers/base_tracker/video_handler.py
So the skellytracker version is writing the frames to the videowriter on each iteration, rather than storing them in a list. Is this what you mean with your first option? The second option is a good idea, and one I'll keep in mind if the annotated video memory issues aren't solved by the current plan.

And in the long term, we've been slowly refactoring our camera backend, which will eventually be responsible for all of the video interfacing. I believe the relevant code is here, although I could be wrong on which branch is most up to date: https://github.com/freemocap/skellycam/blob/development/skellycam/backend/controller/core_functionality/camera_group/video_recorder/video_recorder.py

**Comment by raphCode** [comment]
> Our next release will feature control over how many processes are spun up, so you hopefully won't have to decide between full multiprocessing and no multiprocessing.

Sadly, even a single process almost maxes out the memory in the scenario described, so even two processes are too much.

> So the skellytracker version is writing the frames to the videowriter on each iteration, rather than storing them in a list. Is this what you mean with your first option?

If I understand correctly, yes.

So, in short my understanding is: A new, refactored version is in the work, and it will likely resolve the issue. I do not need to contribute code.

**Comment by philipqueen** [comment]
> So, in short my understanding is: A new, refactored version is in the work, and it will likely resolve the issue. I do not need to contribute code.

Yes, that is correct. On my machine, the development branch is showing a relatively consistent amount of ram usage during processing. If you continue to have ram issues with the development branch or wwith the next release, please let us know!

<img width="207" alt="Screen Shot 2024-01-20 at 10 46 14 AM" src="https://github.com/freemocap/freemocap/assets/24758117/b6b3dec8-3ee9-46b0-a62d-0104b9a861e6">
