### ISSUE TITLE
Unused code in mediapipe pose extraction?

### ISSUE THREAD

**Issue by raphCode** [freemocap/freemocap#528]
I believe the following code region does not do anything, because the results are not used anywhere.
Please correct me if I am wrong.
https://github.com/freemocap/freemocap/blob/7616f65d18dcf192f70f538027f712db5e73e37f/freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/mediapipe_skeleton_detector.py#L160-L171

The code is in a loop iterating over video frames, so it might boost performance if it indeed can be eliminated.

The function `list_of_mediapipe_results_to_npy_arrays` is called again before returning from the function, so I think the above code inside the loop exists by mistake. That it was added by a [big commit](https://github.com/freemocap/freemocap/pull/407) further confirms my suspicion...
https://github.com/freemocap/freemocap/blob/7616f65d18dcf192f70f538027f712db5e73e37f/freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/mediapipe_skeleton_detector.py#L198-L205

**Comment by philipqueen** [comment]
Hey @raphCode, you're totally correct, that code doesn't do anything. It's been fixed in the development branch already, which has switched over to doing pose estimation with the separate repo [skellytracker](https://github.com/freemocap/skellytracker/tree/main/skellytracker). 
Good catch, and since you're interested in the code base, I highly recommend you go look at the [development branch](https://github.com/freemocap/freemocap/pull/510). We're working on a few things there and in activate PRs in preparation for our next minor release (1.1)
