### ISSUE TITLE
[BUG] Issue with the pipeline check

### ISSUE THREAD

**Issue by aaroncherian** [freemocap/freemocap#622]
I got a report/question by email about a niche bug that occurred in the `processing_pipeline_check` function. They were trying to just run 2d image tracking, and so had unchecked `Run 3d triangulation`. However, that gave them this error, which I reproduced and pasted down below:

```
Number of `.mp4`'s in C:\Users\aaron\FreeMocap_Data\recording_sessions\freemocap_sample_data\synchronized_videos: 3
2024-07-24 10:44:10,843 - freemocap.data_layer.recording_models.recording_info_model - INFO - Number of `.mp4`'s in C:\Users\aaron\FreeMocap_Data\recording_sessions\freemocap_sample_data\synchronized_videos: 3
[2024-07-24T10:44:10.844817] [Δt:0.000801s] [   DEBUG] [freemocap.data_layer.recording_models.recording_info_model] [recording_info_model:get_number_of_frames_in_videos():286] [PID:72676:Process-1 TID:76512:MainThread ] No 'timestamps' 
directory, finding frame counts from synchronized videos
[2024-07-24T10:44:10.866817] [Δt:0.025000s] [   ERROR] [freemocap.core_processes.process_motion_capture_videos.process_recording_folder] [process_recording_folder:process_recording_folder():64] [PID:72676:Process-1 TID:76512:MainThread 
] processing parameters are not valid for recording status
2024-07-24 10:44:10,866 - freemocap.core_processes.process_motion_capture_videos.process_recording_folder - ERROR - processing parameters are not valid for recording status
Process Process-1:
Traceback (most recent call last):
  File "c:\Users\aaron\anaconda3\envs\freemocap_dev_2\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
message: [2024-07-24T10:44:10.0866] [ERROR] [freemocap.core_processes.process_motion_capture_videos.process_recording_folder] [Process:72676 Thread:76512] ::::: [freemocap.core_processes.process_motion_capture_videos.process_recording_folder:process_recording_folder():64] |||| processing parameters are not valid for recording status.
  File "c:\Users\aaron\anaconda3\envs\freemocap_dev_2\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\aaron\Documents\GitHub\freemocap\freemocap\core_processes\process_motion_capture_videos\process_recording_folder.py", line 67, in process_recording_folder
    raise e
  File "C:\Users\aaron\Documents\GitHub\freemocap\freemocap\core_processes\process_motion_capture_videos\process_recording_folder.py", line 62, in process_recording_folder
    processing_pipeline_check(processing_parameters=recording_processing_parameter_model)
  File "C:\Users\aaron\Documents\GitHub\freemocap\freemocap\core_processes\process_motion_capture_videos\processing_pipeline_functions\pipeline_check.py", line 24, in processing_pipeline_check
    raise FileNotFoundError(
FileNotFoundError: No 3d data found at: C:\Users\aaron\FreeMocap_Data\recording_sessions\freemocap_sample_data\output_data\mediapipe_skeleton_3d.npy
```

The issue seems to be that if you're running a completely new recording and only enable 2D image tracking, this section will run:
```
if not processing_parameters.anipose_triangulate_3d_parameters_model.run_3d_triangulation:
        if not status_check_dict["data3d_status_check"]:
            raise FileNotFoundError(
                f"No 3d data found at: {processing_parameters.recording_info_model.data_3d_npy_file_path}"
            )
 ```
 
 And will raise that `FileNotFoundError`. 
 
 My initial question is, is there any reason we raise an error about the 3D data not existing if `Run 3d triangulation` is disabled? The case of people wanted to just do 2d image tracking is a pretty niche one IMO, but I'm just wondering about this on a more general scale of why we do this specific search for the 3d file at this specific juncture?

**Comment by philipqueen** [comment]
This looks like a bug in the logic to me - I wonder if it stems from how the “run_triangulation” feature used to have inverted logic and be called “skip_3d_triangulation”. I’m busy during the day today but I think a patch removing the offending “not” in the first “if” check would be in order, and I’ll take a closer look at the rest of the checks soon

**Comment by aaroncherian** [comment]
I don't think that's the patch we would want. Currently the 3D data check (and the same logic for the 2D data) asks:

_If you **are not** triangulating data, does 3d data already exist? If it doesn't, raise an error._ 

The patch you suggested, removing the first `not` would essentially make this:

_If you **are triangulating** data, does 3d data exist? If it doesn't, raise an error._

Meaning if the user doesn't have 3d data and was trying to triangulate it, they would get a `FileNotFound` error. Do I have that right?

Given that this specific pipeline check happens before running the pipeline, the question that jumps out at me is: what advantage does checking that our 3d data exists before running the pipeline that potentially generates that 3d data give us?

**Comment by philipqueen** [comment]
You're right, I was definitely responding to this too early in the morning.

The check is to make sure that 3d data exists by the end of the `run 3d triangulation` part of the pipeline. If it doesn't exist at that point, all of the rest of the pipeline will fail, including the jupyter notebook generation and blender export. And it may fail with a less descriptive error, causing confusion. That's why we put the pipeline check in place. 

Currently we don't have "exit the pipeline early" functionality. That's something we could talk about adding, but I also wonder the point if 2d data could be retrieved by just calling skellytracker. I'd be inclined to just make a better cli entrypoint to skellytracker over making the pipeline logic more complex. Every freemocap user has skellytracker downloaded anyways, so the command could just be `skellytracker path/to/folder/of/videos` and then prompt the user for which tracker and what parameters to use.

**Comment by xpat** [comment]
Just to chime in and confirm that I had a problem processing a single camera video just now (first time trying in months and months).  The error I got was "processing parameters are not valid for recording status."  I searched and came across this issue.  I had unchecked the Run 3d Triangulation box under process but when I re-checked it the processing worked.  

Also, I ran the skellytracker command and pointed it to an .mp4.  It wasn't immediately clear to me what that did.  I saved the terminal output but won't bother you with it unless I can't figure it out.  

One more thing, for the line that reads **Single Video Recording, No Calibration Needed** (Under Process Data), it would be nice to have a radio button there.  The radio button defaults to "Use most recent calibration".  Since I had unchecked the 3d box ad was getting errors, I thought it might have to do with calibration so I tried each of the calibration options until I finally homed in on the line that says calibration wasn't needed.

**Comment by philipqueen** [comment]
Hi @xpat, thanks for the feedback!

It seems like you have a slightly different bug, as whether the `Run 3d Triangulation` box is checked or not shouldn't matter if it's a single video recording. I'll look into fixing that.

As far as the skellytracker command goes, I was suggesting potential functionality, not describing the current behavior. So no need to look into it, it probably just threw some error related to an unexpected/invalid argument. 

As for radio buttons, I'll look into changing the behavior for single camera recordings as well. It may be best to disable all of the radio buttons in this case, or potentially even hide the calibration options (since all the options are ignored for single cameras anyways)

**Comment by xpat** [comment]
@philipqueen Thanks for the clarification.  Have a nice day and thanks receiving my input so nicely.
